// Generated by scripts/generateGeminiImages.mjs
import type { PexelsImageMap } from '../types';

export const generatedImages: PexelsImageMap = {
  "hero": {
    "src": "/generated/hero/1000.webp",
    "srcSet": "/generated/hero/400.webp 400w, /generated/hero/700.webp 700w, /generated/hero/1000.webp 1000w, /generated/hero/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "cta": {
    "src": "/generated/cta/1000.webp",
    "srcSet": "/generated/cta/400.webp 400w, /generated/cta/700.webp 700w, /generated/cta/1000.webp 1000w, /generated/cta/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "quiz": {
    "src": "/generated/quiz/1000.webp",
    "srcSet": "/generated/quiz/400.webp 400w, /generated/quiz/700.webp 700w, /generated/quiz/1000.webp 1000w, /generated/quiz/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "services": {
    "tape-in": {
      "src": "/generated/services/tape-in/1000.webp",
      "srcSet": "/generated/services/tape-in/400.webp 400w, /generated/services/tape-in/700.webp 700w, /generated/services/tape-in/1000.webp 1000w, /generated/services/tape-in/2000.webp 2000w",
      "photographer": "Generated with Google Gemini",
      "photographerUrl": "",
      "pexelsUrl": "",
      "avgColor": ""
    },
    "keratin-bond": {
      "src": "/generated/services/keratin-bond/1000.webp",
      "srcSet": "/generated/services/keratin-bond/400.webp 400w, /generated/services/keratin-bond/700.webp 700w, /generated/services/keratin-bond/1000.webp 1000w, /generated/services/keratin-bond/2000.webp 2000w",
      "photographer": "Generated with Google Gemini",
      "photographerUrl": "",
      "pexelsUrl": "",
      "avgColor": ""
    },
    "hand-tied": {
      "src": "/generated/services/hand-tied/1000.webp",
      "srcSet": "/generated/services/hand-tied/400.webp 400w, /generated/services/hand-tied/700.webp 700w, /generated/services/hand-tied/1000.webp 1000w, /generated/services/hand-tied/2000.webp 2000w",
      "photographer": "Generated with Google Gemini",
      "photographerUrl": "",
      "pexelsUrl": "",
      "avgColor": ""
    },
    "sew-in": {
      "src": "/generated/services/sew-in/1000.webp",
      "srcSet": "/generated/services/sew-in/400.webp 400w, /generated/services/sew-in/700.webp 700w, /generated/services/sew-in/1000.webp 1000w, /generated/services/sew-in/2000.webp 2000w",
      "photographer": "Generated with Google Gemini",
      "photographerUrl": "",
      "pexelsUrl": "",
      "avgColor": ""
    }
  },
  "transformations": {
    "t1_before": {
      "src": "/generated/transformations/t1_before/1000.webp",
      "srcSet": "/generated/transformations/t1_before/400.webp 400w, /generated/transformations/t1_before/700.webp 700w, /generated/transformations/t1_before/1000.webp 1000w, /generated/transformations/t1_before/2000.webp 2000w",
      "photographer": "Generated with Google Gemini",
      "photographerUrl": "",
      "pexelsUrl": "",
      "avgColor": ""
    },
    "t1_after": {
      "src": "/generated/transformations/t1_after/1000.webp",
      "srcSet": "/generated/transformations/t1_after/400.webp 400w, /generated/transformations/t1_after/700.webp 700w, /generated/transformations/t1_after/1000.webp 1000w, /generated/transformations/t1_after/2000.webp 2000w",
      "photographer": "Generated with Google Gemini",
      "photographerUrl": "",
      "pexelsUrl": "",
      "avgColor": ""
    },
    "t2_before": {
      "src": "/generated/transformations/t2_before/1000.webp",
      "srcSet": "/generated/transformations/t2_before/400.webp 400w, /generated/transformations/t2_before/700.webp 700w, /generated/transformations/t2_before/1000.webp 1000w, /generated/transformations/t2_before/2000.webp 2000w",
      "photographer": "Generated with Google Gemini",
      "photographerUrl": "",
      "pexelsUrl": "",
      "avgColor": ""
    },
    "t2_after": {
      "src": "/generated/transformations/t2_after/1000.webp",
      "srcSet": "/generated/transformations/t2_after/400.webp 400w, /generated/transformations/t2_after/700.webp 700w, /generated/transformations/t2_after/1000.webp 1000w, /generated/transformations/t2_after/2000.webp 2000w",
      "photographer": "Generated with Google Gemini",
      "photographerUrl": "",
      "pexelsUrl": "",
      "avgColor": ""
    }
  },
  "gallery": {
    "Blonde": [
      {
        "src": "/generated/gallery/blonde_1/1000.webp",
        "srcSet": "/generated/gallery/blonde_1/400.webp 400w, /generated/gallery/blonde_1/700.webp 700w, /generated/gallery/blonde_1/1000.webp 1000w, /generated/gallery/blonde_1/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      },
      {
        "src": "/generated/gallery/blonde_2/1000.webp",
        "srcSet": "/generated/gallery/blonde_2/400.webp 400w, /generated/gallery/blonde_2/700.webp 700w, /generated/gallery/blonde_2/1000.webp 1000w, /generated/gallery/blonde_2/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      },
      {
        "src": "/generated/gallery/blonde_3/1000.webp",
        "srcSet": "/generated/gallery/blonde_3/400.webp 400w, /generated/gallery/blonde_3/700.webp 700w, /generated/gallery/blonde_3/1000.webp 1000w, /generated/gallery/blonde_3/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      }
    ],
    "Volume": [
      {
        "src": "/generated/gallery/volume_1/1000.webp",
        "srcSet": "/generated/gallery/volume_1/400.webp 400w, /generated/gallery/volume_1/700.webp 700w, /generated/gallery/volume_1/1000.webp 1000w, /generated/gallery/volume_1/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      },
      {
        "src": "/generated/gallery/volume_2/1000.webp",
        "srcSet": "/generated/gallery/volume_2/400.webp 400w, /generated/gallery/volume_2/700.webp 700w, /generated/gallery/volume_2/1000.webp 1000w, /generated/gallery/volume_2/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      },
      {
        "src": "/generated/gallery/volume_3/1000.webp",
        "srcSet": "/generated/gallery/volume_3/400.webp 400w, /generated/gallery/volume_3/700.webp 700w, /generated/gallery/volume_3/1000.webp 1000w, /generated/gallery/volume_3/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      }
    ],
    "Length": [
      {
        "src": "/generated/gallery/length_1/1000.webp",
        "srcSet": "/generated/gallery/length_1/400.webp 400w, /generated/gallery/length_1/700.webp 700w, /generated/gallery/length_1/1000.webp 1000w, /generated/gallery/length_1/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      },
      {
        "src": "/generated/gallery/length_2/1000.webp",
        "srcSet": "/generated/gallery/length_2/400.webp 400w, /generated/gallery/length_2/700.webp 700w, /generated/gallery/length_2/1000.webp 1000w, /generated/gallery/length_2/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      },
      {
        "src": "/generated/gallery/length_3/1000.webp",
        "srcSet": "/generated/gallery/length_3/400.webp 400w, /generated/gallery/length_3/700.webp 700w, /generated/gallery/length_3/1000.webp 1000w, /generated/gallery/length_3/2000.webp 2000w",
        "photographer": "Generated with Google Gemini",
        "photographerUrl": "",
        "pexelsUrl": "",
        "avgColor": ""
      }
    ]
  }
} as const;
