// This file is generated by scripts/fetchPexelsImages.mjs
// Do not edit manually.

import type { ImageAsset, PexelsImageMap } from '../types';

export const pexelsImages: PexelsImageMap = {
  "hero": {
    "src": "https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "srcSet": "https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
    "photographer": "Engin Akyurt",
    "photographerUrl": "https://www.pexels.com/@enginakyurt",
    "pexelsUrl": "https://www.pexels.com/photo/photo-of-woman-s-hairstyle-3065171/",
    "avgColor": "#AB9C93"
  },
  "cta": {
    "src": "https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "srcSet": "https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
    "photographer": "Engin Akyurt",
    "photographerUrl": "https://www.pexels.com/@enginakyurt",
    "pexelsUrl": "https://www.pexels.com/photo/photo-of-woman-s-hairstyle-3065171/",
    "avgColor": "#AB9C93"
  },
  "quiz": {
    "src": "https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "srcSet": "https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/3065171/pexels-photo-3065171.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
    "photographer": "Engin Akyurt",
    "photographerUrl": "https://www.pexels.com/@enginakyurt",
    "pexelsUrl": "https://www.pexels.com/photo/photo-of-woman-s-hairstyle-3065171/",
    "avgColor": "#AB9C93"
  },
  "services": {
    "tape-in": {
      "src": "https://images.pexels.com/photos/8468148/pexels-photo-8468148.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "srcSet": "https://images.pexels.com/photos/8468148/pexels-photo-8468148.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/8468148/pexels-photo-8468148.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/8468148/pexels-photo-8468148.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/8468148/pexels-photo-8468148.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
      "photographer": "Nataliya Vaitkevich",
      "photographerUrl": "https://www.pexels.com/@n-voitkevich",
      "pexelsUrl": "https://www.pexels.com/photo/gray-and-silver-scissors-on-white-surface-8468148/",
      "avgColor": "#BEBEC0"
    },
    "keratin-bond": {
      "src": "https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "srcSet": "https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
      "photographer": "Alina Skazka",
      "photographerUrl": "https://www.pexels.com/@alinaskazka",
      "pexelsUrl": "https://www.pexels.com/photo/two-blonde-hair-extensions-on-a-pink-background-18614262/",
      "avgColor": "#CFBCB6"
    },
    "hand-tied": {
      "src": "https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "srcSet": "https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
      "photographer": "Alina Skazka",
      "photographerUrl": "https://www.pexels.com/@alinaskazka",
      "pexelsUrl": "https://www.pexels.com/photo/two-blonde-hair-extensions-on-a-pink-background-18614262/",
      "avgColor": "#CFBCB6"
    },
    "sew-in": {
      "src": "https://images.pexels.com/photos/6923241/pexels-photo-6923241.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "srcSet": "https://images.pexels.com/photos/6923241/pexels-photo-6923241.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/6923241/pexels-photo-6923241.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/6923241/pexels-photo-6923241.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/6923241/pexels-photo-6923241.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
      "photographer": "RDNE Stock project",
      "photographerUrl": "https://www.pexels.com/@rdne",
      "pexelsUrl": "https://www.pexels.com/photo/blonde-haired-woman-in-blue-sleeveless-top-6923241/",
      "avgColor": "#52ADB8"
    }
  },
  "transformations": {
    "t1_before": {
      "src": "https://images.pexels.com/photos/20272960/pexels-photo-20272960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "srcSet": "https://images.pexels.com/photos/20272960/pexels-photo-20272960.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/20272960/pexels-photo-20272960.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/20272960/pexels-photo-20272960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/20272960/pexels-photo-20272960.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
      "photographer": "Mauricio Casas",
      "photographerUrl": "https://www.pexels.com/@mauricio-casas-454804780",
      "pexelsUrl": "https://www.pexels.com/photo/woman-with-brown-hair-20272960/",
      "avgColor": "#29201B"
    },
    "t1_after": {
      "src": "https://images.pexels.com/photos/20697497/pexels-photo-20697497.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "srcSet": "https://images.pexels.com/photos/20697497/pexels-photo-20697497.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/20697497/pexels-photo-20697497.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/20697497/pexels-photo-20697497.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/20697497/pexels-photo-20697497.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
      "photographer": "Natalia Maik",
      "photographerUrl": "https://www.pexels.com/@natalia-maik-924569986",
      "pexelsUrl": "https://www.pexels.com/photo/brunette-woman-with-bouquet-of-flowers-in-hands-20697497/",
      "avgColor": "#979086"
    },
    "t2_before": {
      "src": "https://images.pexels.com/photos/10117482/pexels-photo-10117482.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "srcSet": "https://images.pexels.com/photos/10117482/pexels-photo-10117482.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/10117482/pexels-photo-10117482.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/10117482/pexels-photo-10117482.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/10117482/pexels-photo-10117482.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
      "photographer": "Anna Belousova",
      "photographerUrl": "https://www.pexels.com/@anna-belousova-130658517",
      "pexelsUrl": "https://www.pexels.com/photo/white-and-green-wooden-house-10117482/",
      "avgColor": "#3F4A44"
    },
    "t2_after": {
      "src": "https://images.pexels.com/photos/16128149/pexels-photo-16128149.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "srcSet": "https://images.pexels.com/photos/16128149/pexels-photo-16128149.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/16128149/pexels-photo-16128149.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/16128149/pexels-photo-16128149.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/16128149/pexels-photo-16128149.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
      "photographer": "Julia",
      "photographerUrl": "https://www.pexels.com/@julia-463646514",
      "pexelsUrl": "https://www.pexels.com/photo/back-view-of-naked-woman-16128149/",
      "avgColor": "#C4C4C4"
    }
  },
  "gallery": {
    "Blonde": [
      {
        "src": "https://images.pexels.com/photos/7440055/pexels-photo-7440055.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/7440055/pexels-photo-7440055.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/7440055/pexels-photo-7440055.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/7440055/pexels-photo-7440055.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/7440055/pexels-photo-7440055.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "pexelsUrl": "https://www.pexels.com/photo/photo-of-a-woman-getting-her-hair-styled-7440055/",
        "avgColor": "#9E9A98"
      },
      {
        "src": "https://images.pexels.com/photos/7440131/pexels-photo-7440131.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/7440131/pexels-photo-7440131.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/7440131/pexels-photo-7440131.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/7440131/pexels-photo-7440131.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/7440131/pexels-photo-7440131.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "pexelsUrl": "https://www.pexels.com/photo/photo-of-a-person-s-hand-touching-blond-hair-7440131/",
        "avgColor": "#B3ABA5"
      },
      {
        "src": "https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Engin Akyurt",
        "photographerUrl": "https://www.pexels.com/@enginakyurt",
        "pexelsUrl": "https://www.pexels.com/photo/photo-of-hairstyle-3065207/",
        "avgColor": "#8C7C6D"
      },
      {
        "src": "https://images.pexels.com/photos/3738359/pexels-photo-3738359.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/3738359/pexels-photo-3738359.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/3738359/pexels-photo-3738359.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/3738359/pexels-photo-3738359.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/3738359/pexels-photo-3738359.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Polina Tankilevitch",
        "photographerUrl": "https://www.pexels.com/@polina-tankilevitch",
        "pexelsUrl": "https://www.pexels.com/photo/person-ironing-a-woman-s-hair-3738359/",
        "avgColor": "#A29C97"
      },
      {
        "src": "https://images.pexels.com/photos/973403/pexels-photo-973403.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/973403/pexels-photo-973403.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/973403/pexels-photo-973403.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/973403/pexels-photo-973403.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/973403/pexels-photo-973403.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Element5 Digital",
        "photographerUrl": "https://www.pexels.com/@element5",
        "pexelsUrl": "https://www.pexels.com/photo/woman-curling-her-hair-973403/",
        "avgColor": "#B6A391"
      },
      {
        "src": "https://images.pexels.com/photos/3738338/pexels-photo-3738338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/3738338/pexels-photo-3738338.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/3738338/pexels-photo-3738338.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/3738338/pexels-photo-3738338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/3738338/pexels-photo-3738338.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Polina Tankilevitch",
        "photographerUrl": "https://www.pexels.com/@polina-tankilevitch",
        "pexelsUrl": "https://www.pexels.com/photo/selective-focus-photo-of-person-ironing-a-woman-s-hair-3738338/",
        "avgColor": "#817E7D"
      }
    ],
    "Volume": [
      {
        "src": "https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/18614262/pexels-photo-18614262.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Alina Skazka",
        "photographerUrl": "https://www.pexels.com/@alinaskazka",
        "pexelsUrl": "https://www.pexels.com/photo/two-blonde-hair-extensions-on-a-pink-background-18614262/",
        "avgColor": "#CFBCB6"
      },
      {
        "src": "https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/3065207/pexels-photo-3065207.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Engin Akyurt",
        "photographerUrl": "https://www.pexels.com/@enginakyurt",
        "pexelsUrl": "https://www.pexels.com/photo/photo-of-hairstyle-3065207/",
        "avgColor": "#8C7C6D"
      },
      {
        "src": "https://images.pexels.com/photos/31950138/pexels-photo-31950138.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/31950138/pexels-photo-31950138.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/31950138/pexels-photo-31950138.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/31950138/pexels-photo-31950138.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/31950138/pexels-photo-31950138.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Golboo Maghooli",
        "photographerUrl": "https://www.pexels.com/@golboo",
        "pexelsUrl": "https://www.pexels.com/photo/elegant-gray-hair-updo-for-special-occasions-31950138/",
        "avgColor": "#616775"
      },
      {
        "src": "https://images.pexels.com/photos/21412169/pexels-photo-21412169.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/21412169/pexels-photo-21412169.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/21412169/pexels-photo-21412169.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/21412169/pexels-photo-21412169.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/21412169/pexels-photo-21412169.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Milangel Melendez",
        "photographerUrl": "https://www.pexels.com/@milangel-melendez-1162121836",
        "pexelsUrl": "https://www.pexels.com/photo/close-up-of-an-eye-with-glued-eyelashes-21412169/",
        "avgColor": "#9B8881"
      },
      {
        "src": "https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Alina Skazka",
        "photographerUrl": "https://www.pexels.com/@alinaskazka",
        "pexelsUrl": "https://www.pexels.com/photo/bundles-of-human-hair-14730867/",
        "avgColor": "#C3BAB5"
      },
      {
        "src": "https://images.pexels.com/photos/2474255/pexels-photo-2474255.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/2474255/pexels-photo-2474255.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/2474255/pexels-photo-2474255.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/2474255/pexels-photo-2474255.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/2474255/pexels-photo-2474255.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Dellon Thomas",
        "photographerUrl": "https://www.pexels.com/@elsimage",
        "pexelsUrl": "https://www.pexels.com/photo/photo-of-woman-wearing-brown-dress-2474255/",
        "avgColor": "#B5A8A2"
      }
    ],
    "Length": [
      {
        "src": "https://images.pexels.com/photos/13709921/pexels-photo-13709921.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/13709921/pexels-photo-13709921.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/13709921/pexels-photo-13709921.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/13709921/pexels-photo-13709921.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/13709921/pexels-photo-13709921.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Jaycee300s",
        "photographerUrl": "https://www.pexels.com/@jaycee300s-3059779",
        "pexelsUrl": "https://www.pexels.com/photo/a-beautiful-woman-in-purple-jacket-and-pants-wearing-black-boots-13709921/",
        "avgColor": "#5D5668"
      },
      {
        "src": "https://images.pexels.com/photos/14730877/pexels-photo-14730877.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/14730877/pexels-photo-14730877.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/14730877/pexels-photo-14730877.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/14730877/pexels-photo-14730877.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/14730877/pexels-photo-14730877.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Alina Skazka",
        "photographerUrl": "https://www.pexels.com/@alinaskazka",
        "pexelsUrl": "https://www.pexels.com/photo/hand-holding-additional-hair-14730877/",
        "avgColor": "#EBD6E7"
      },
      {
        "src": "https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/14730867/pexels-photo-14730867.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Alina Skazka",
        "photographerUrl": "https://www.pexels.com/@alinaskazka",
        "pexelsUrl": "https://www.pexels.com/photo/bundles-of-human-hair-14730867/",
        "avgColor": "#C3BAB5"
      },
      {
        "src": "https://images.pexels.com/photos/14730875/pexels-photo-14730875.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/14730875/pexels-photo-14730875.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/14730875/pexels-photo-14730875.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/14730875/pexels-photo-14730875.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/14730875/pexels-photo-14730875.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Alina Skazka",
        "photographerUrl": "https://www.pexels.com/@alinaskazka",
        "pexelsUrl": "https://www.pexels.com/photo/shades-of-natural-blond-hair-on-light-pink-background-14730875/",
        "avgColor": "#D6CACA"
      },
      {
        "src": "https://images.pexels.com/photos/14730864/pexels-photo-14730864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/14730864/pexels-photo-14730864.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/14730864/pexels-photo-14730864.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/14730864/pexels-photo-14730864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/14730864/pexels-photo-14730864.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "Alina Skazka",
        "photographerUrl": "https://www.pexels.com/@alinaskazka",
        "pexelsUrl": "https://www.pexels.com/photo/hair-and-pincers-on-white-background-14730864/",
        "avgColor": "#C9C8C4"
      },
      {
        "src": "https://images.pexels.com/photos/6923240/pexels-photo-6923240.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "srcSet": "https://images.pexels.com/photos/6923240/pexels-photo-6923240.jpeg?auto=compress&cs=tinysrgb&h=130 400w, https://images.pexels.com/photos/6923240/pexels-photo-6923240.jpeg?auto=compress&cs=tinysrgb&h=350 700w, https://images.pexels.com/photos/6923240/pexels-photo-6923240.jpeg?auto=compress&cs=tinysrgb&h=650&w=940 1000w, https://images.pexels.com/photos/6923240/pexels-photo-6923240.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 2000w",
        "photographer": "RDNE Stock project",
        "photographerUrl": "https://www.pexels.com/@rdne",
        "pexelsUrl": "https://www.pexels.com/photo/upside-down-photo-of-blonde-hair-on-light-blue-background-6923240/",
        "avgColor": "#66B5C0"
      }
    ]
  }
} as const;

export type { ImageAsset };
