// Generated by scripts/generateStylePreviews.mjs
import type { ImageAsset } from '../types';

export const stylePreviews: Record<string, ImageAsset> = {
  "extensions-soft-waves": {
    "src": "/generated/style-previews/extensions-soft-waves/1000.webp",
    "srcSet": "/generated/style-previews/extensions-soft-waves/400.webp 400w, /generated/style-previews/extensions-soft-waves/700.webp 700w, /generated/style-previews/extensions-soft-waves/1000.webp 1000w, /generated/style-previews/extensions-soft-waves/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "extensions-natural-blend": {
    "src": "/generated/style-previews/extensions-natural-blend/1000.webp",
    "srcSet": "/generated/style-previews/extensions-natural-blend/400.webp 400w, /generated/style-previews/extensions-natural-blend/700.webp 700w, /generated/style-previews/extensions-natural-blend/1000.webp 1000w, /generated/style-previews/extensions-natural-blend/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "extensions-volume-set": {
    "src": "/generated/style-previews/extensions-volume-set/1000.webp",
    "srcSet": "/generated/style-previews/extensions-volume-set/400.webp 400w, /generated/style-previews/extensions-volume-set/700.webp 700w, /generated/style-previews/extensions-volume-set/1000.webp 1000w, /generated/style-previews/extensions-volume-set/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "extensions-length-set": {
    "src": "/generated/style-previews/extensions-length-set/1000.webp",
    "srcSet": "/generated/style-previews/extensions-length-set/400.webp 400w, /generated/style-previews/extensions-length-set/700.webp 700w, /generated/style-previews/extensions-length-set/1000.webp 1000w, /generated/style-previews/extensions-length-set/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "extensions-glam-density": {
    "src": "/generated/style-previews/extensions-glam-density/1000.webp",
    "srcSet": "/generated/style-previews/extensions-glam-density/400.webp 400w, /generated/style-previews/extensions-glam-density/700.webp 700w, /generated/style-previews/extensions-glam-density/1000.webp 1000w, /generated/style-previews/extensions-glam-density/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "extensions-sleek-straight": {
    "src": "/generated/style-previews/extensions-sleek-straight/1000.webp",
    "srcSet": "/generated/style-previews/extensions-sleek-straight/400.webp 400w, /generated/style-previews/extensions-sleek-straight/700.webp 700w, /generated/style-previews/extensions-sleek-straight/1000.webp 1000w, /generated/style-previews/extensions-sleek-straight/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "color-neutral-gloss": {
    "src": "/generated/style-previews/color-neutral-gloss/1000.webp",
    "srcSet": "/generated/style-previews/color-neutral-gloss/400.webp 400w, /generated/style-previews/color-neutral-gloss/700.webp 700w, /generated/style-previews/color-neutral-gloss/1000.webp 1000w, /generated/style-previews/color-neutral-gloss/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "color-caramel-bronde": {
    "src": "/generated/style-previews/color-caramel-bronde/1000.webp",
    "srcSet": "/generated/style-previews/color-caramel-bronde/400.webp 400w, /generated/style-previews/color-caramel-bronde/700.webp 700w, /generated/style-previews/color-caramel-bronde/1000.webp 1000w, /generated/style-previews/color-caramel-bronde/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "color-cool-ash-brunette": {
    "src": "/generated/style-previews/color-cool-ash-brunette/1000.webp",
    "srcSet": "/generated/style-previews/color-cool-ash-brunette/400.webp 400w, /generated/style-previews/color-cool-ash-brunette/700.webp 700w, /generated/style-previews/color-cool-ash-brunette/1000.webp 1000w, /generated/style-previews/color-cool-ash-brunette/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "color-champagne-balayage": {
    "src": "/generated/style-previews/color-champagne-balayage/1000.webp",
    "srcSet": "/generated/style-previews/color-champagne-balayage/400.webp 400w, /generated/style-previews/color-champagne-balayage/700.webp 700w, /generated/style-previews/color-champagne-balayage/1000.webp 1000w, /generated/style-previews/color-champagne-balayage/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "color-copper-glow": {
    "src": "/generated/style-previews/color-copper-glow/1000.webp",
    "srcSet": "/generated/style-previews/color-copper-glow/400.webp 400w, /generated/style-previews/color-copper-glow/700.webp 700w, /generated/style-previews/color-copper-glow/1000.webp 1000w, /generated/style-previews/color-copper-glow/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  },
  "color-espresso-depth": {
    "src": "/generated/style-previews/color-espresso-depth/1000.webp",
    "srcSet": "/generated/style-previews/color-espresso-depth/400.webp 400w, /generated/style-previews/color-espresso-depth/700.webp 700w, /generated/style-previews/color-espresso-depth/1000.webp 1000w, /generated/style-previews/color-espresso-depth/2000.webp 2000w",
    "photographer": "Generated with Google Gemini",
    "photographerUrl": "",
    "pexelsUrl": "",
    "avgColor": ""
  }
} as const;
